version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mts121101
      POSTGRES_DATABASE: user_management
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
      SECRET: your_secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - db
   
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mts121101
      POSTGRES_DB: user_management
    ports:
      - 5433:5432

